use_frameworks!

platform :ios, '9.0'

target 'TestThisFrameworkA_Example' do
  pod 'TestThisFrameworkA', :path => '../'

  target 'TestThisFrameworkA_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
